export const GET_CONTACTS_LOADING = `GET_CONTACTS_LOADING`;
export const GET_CONTACTS_SUCCESS = `GET_CONTACTS_SUCCESS`;
export const GET_CONTACTS_ERROR = `GET_CONTACTS_ERROR`;

export const LOGOUT = `LOGOUT`;
export const CLEAR_ADD_CONTACT = `CLEAR_ADD_CONTACT`;

export const ADD_CONTACT_LOADING = `ADD_CONTACT_LOADING`;
export const ADD_CONTACT_SUCCESS = `ADD_CONTACT_SUCCESS`;
export const ADD_CONTACT_ERROR = `ADD_CONTACT_ERROR`;
